#!/usr/bin/env python3
"""Deterministic randomized regression for the queued IAIC processor."""

from __future__ import annotations

import os
import random
import shutil
import subprocess
import tempfile
from pathlib import Path

from iaic_operator import pack_int8


ROOT = Path(__file__).resolve().parents[1]
LANES = 16
SEED = 20260828
VECTOR_COUNT = 64


def make_vectors() -> list[tuple[int, int, int]]:
    rng = random.Random(SEED)
    vectors = []
    for _ in range(VECTOR_COUNT):
        activations = [rng.randint(-128, 127) for _ in range(LANES)]
        weights = [rng.randint(-128, 127) for _ in range(LANES)]
        vectors.append((pack_int8(activations), pack_int8(weights), sum(a * w for a, w in zip(activations, weights))))
    return vectors


def testbench(vectors: list[tuple[int, int, int]]) -> str:
    lines = [
        f"// Generated by tools/test_processor_random.py; seed {SEED}.",
        "module ii_inference_processor_random_tb;",
        f"    localparam int LANES = {LANES};",
        f"    localparam int VECTOR_COUNT = {len(vectors)};",
        "    logic clk = 1'b0, rst_n = 1'b0;",
        "    logic csr_valid = 1'b0, csr_write = 1'b0;",
        "    logic [3:0] csr_addr = '0;",
        "    logic [31:0] csr_wdata = '0;",
        "    logic csr_ready, csr_rsp_valid;",
        "    logic [31:0] csr_rdata;",
        "    logic cmd_valid = 1'b0, cmd_ready;",
        "    logic [LANES*8-1:0] cmd_activations = '0, cmd_weights = '0;",
        "    logic result_valid, result_ready = 1'b0;",
        "    logic signed [31:0] result;",
        "    logic busy, done, irq;",
        "    integer expected [0:VECTOR_COUNT-1];",
        "    integer received = 0;",
        "    integer cycle = 0;",
        "",
        "    always #5 clk = ~clk;",
        "    always @(negedge clk) begin",
        "        result_ready = ((cycle % 5) != 1);",
        "        cycle = cycle + 1;",
        "    end",
        "",
        "    ii_inference_processor #(.LANES(LANES), .CMD_QUEUE_DEPTH(4)) dut (",
        "        .clk(clk), .rst_n(rst_n),",
        "        .csr_valid(csr_valid), .csr_write(csr_write), .csr_addr(csr_addr),",
        "        .csr_wdata(csr_wdata), .csr_ready(csr_ready),",
        "        .csr_rsp_valid(csr_rsp_valid), .csr_rdata(csr_rdata),",
        "        .cmd_valid(cmd_valid), .cmd_ready(cmd_ready),",
        "        .cmd_activations(cmd_activations), .cmd_weights(cmd_weights),",
        "        .result_valid(result_valid), .result_ready(result_ready),",
        "        .result(result), .busy(busy), .done(done), .irq(irq)",
        "    );",
        "",
        "    always @(posedge clk) begin",
        "        // Sample handshake signals before the DUT's nonblocking updates.",
        "        if (result_valid && result_ready) begin",
        "            if (received >= VECTOR_COUNT || result !== expected[received]) begin",
        "                $fatal(1, \"result %0d failed: got %0d expected %0d\", received, result, expected[received]);",
        "            end",
        "            received = received + 1;",
        "        end",
        "    end",
        "",
        "    initial begin",
    ]
    lines.extend(f"        expected[{index}] = {expected};" for index, (_, _, expected) in enumerate(vectors))
    lines.extend([
        "        repeat (2) @(negedge clk);",
        "        rst_n = 1'b1;",
        "        @(negedge clk);",
        "        csr_addr = 4'h0;",
        "        csr_wdata = 32'h0000_0001;",
        "        csr_write = 1'b1;",
        "        csr_valid = 1'b1;",
        "        @(posedge clk); #1;",
        "        if (!csr_rsp_valid) $fatal(1, \"missing enable response\");",
        "        csr_valid = 1'b0;",
        "        csr_write = 1'b0;",
    ])
    for activations, weights, _ in vectors:
        lines.extend([
            "        while (1) begin",
            "            @(negedge clk);",
            "            if (cmd_ready) begin",
            f"                cmd_activations = 128'h{activations:032x};",
            f"                cmd_weights = 128'h{weights:032x};",
            "                cmd_valid = 1'b1;",
            "                break;",
            "            end",
            "        end",
            "        @(posedge clk); #1;",
            "        cmd_valid = 1'b0;",
        ])
    lines.extend([
        "        wait (received == VECTOR_COUNT);",
        "        #2;",
        "        if (!done || busy) $fatal(1, \"processor did not finish cleanly: done=%b busy=%b valid=%b received=%0d\", done, busy, result_valid, received);",
        f"        $display(\"ii_inference_processor_random_tb: PASS (%0d vectors, seed %0d)\", VECTOR_COUNT, {SEED});",
        "        $finish;",
        "    end",
        "endmodule",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    simulator = os.environ.get("SIM", "iverilog")
    if shutil.which(simulator) is None:
        raise SystemExit(f"simulator not found: {simulator}")
    vectors = make_vectors()
    with tempfile.TemporaryDirectory(prefix="iaic-processor-random-") as directory:
        work = Path(directory)
        testbench_path = work / "ii_inference_processor_random_tb.sv"
        output_path = work / "ii_inference_processor_random_tb"
        testbench_path.write_text(testbench(vectors), encoding="utf-8")
        subprocess.run(
            [
                simulator, "-g2012", "-Wall", "-o", str(output_path),
                str(ROOT / "rtl/ii_dot_product.sv"),
                str(ROOT / "rtl/ii_dot_product_stream.sv"),
                str(ROOT / "rtl/ii_inference_processor.sv"),
                str(testbench_path),
            ],
            check=True,
            cwd=ROOT,
        )
        subprocess.run(["vvp", str(output_path)], check=True, cwd=ROOT)


if __name__ == "__main__":
    main()
